version: '3.1'

services:

  server:
    image: chewbacca-server
    restart: always
    ports:
      - "8080:8080"
    environment:
      APP_DB_USERNAME: postgres
      APP_DB_PASSWORD: postgres
      APP_DB_NAME: postgres

  db:
    image: postgres
    restart: always
