version: '3.1'

services:

  server:
    image: chewbacca-server
    restart: always
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres

  db:
    image: postgres
    restart: always
