version: '3.1'

services:

  database:
    image: postgres
    restart: always
    networks:
      new:
        aliases:
          - db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: chewbacca

  migrate:
    image: migrate/migrate
    networks:
        - new
    volumes:
        - ./app/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:postgres@database:5432/chewbacca?sslmode=disable", "up"]
    links: 
        - database

networks:
  new:
